Make the KEEP_SVG_OPTION option into a tristate
Merge the TAR and the --keep-svg options into a tristate svg/tar/none.
As the three options are depended on each other, it's more easy to use
to merge into one tristate option.

Signed-off-by: Gavin Guo <gavin.guo@canonical.com>

diff --git a/flamegraph-cpu b/flamegraph-cpu
--- a/flamegraph-cpu
+++ b/flamegraph-cpu
@@ -7,7 +7,7 @@ FPATH=`dirname $0`"/"
 FPERF="`dirname $0`/perf-output"
 GREP_STRINGS=""
 KEEP_SVG=false
-KEEP_SVG_OPTION="-t" # tar the perf.data by default
+KEEP_SVG_OPTION=
 ONESHOT=false
 PERF_CMD=""
 PERF_DATA="perf.cpu"
@@ -98,6 +98,14 @@ perf_periodically_collect() {
 			# clean up the perf.data
 			if $KEEP_SVG; then
 				rm $PERF_DATA_FINAL
+			else
+				if [ -e "$FPERF"/`basename "$PERF_DATA_FINAL"`.zip ]; then
+					echo "Append $PERF_DATA_FINAL to "$FPERF"/`basename "$PERF_DATA_FINAL"`.zip"
+					# tar.gz is generated by easy-flamegraph.sh and append the perf.data in.
+					zip -u "$FPERF"/`basename "$PERF_DATA_FINAL"`.zip "$PERF_DATA_FINAL"
+					rm $PERF_DATA_FINAL
+				fi
+
 			fi
 		) &
 
@@ -193,14 +201,6 @@ exit_work() {
 
 	kill_child_processes 1 $$
 
-	if $TAR; then
-		DATE=$(date +%Y-%m-%d_%H%M%S)
-		if [ ! -z "$(ls -A "${FPERF}")" ]; then
-			tar zcvf "${FPATH}"flamegraph-cpu-"${DATE}".tar.gz "${FPERF}"
-			echo "Please send back "${FPATH}"flamegraph-cpu-"${DATE}".tar.gz"
-		fi
-	fi
-
 	# kill -9 $(ps -9 pgid= $$) can do the trick to kill the process group too.
 	#PGID=$(ps -o pgid= $$)
 
@@ -231,6 +231,7 @@ do
 			;;
 		-t)
 			TAR=true
+			KEEP_SVG_OPTION="-t"
 			shift
 			;;
 		--clean-probes)
@@ -261,6 +262,10 @@ do
 			;;
 	esac
 done
+
+# -t is to tar the intermediate files which is conflicted with the --keep-svg
+# which keeps only the .svg file
+[[ "$TAR" == "true" ]] && [[ "$KEEP_SVG" == "true" ]] && echo "Cannot set '-t' and '--keep-svg' together!" && exit 1
 
 # append the string of the profiled process name to differentiate the perf.data
 [[ "$APPEND_STRINGS" != "" ]] && PERF_DATA=$PERF_DATA.$APPEND_STRINGS$PID
